#ifndef BOOT_STATE_READER_H
#define BOOT_STATE_READER_H

/* Generated by flatcc 0.3.4 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#ifndef alignas
#include <stdalign.h>
#endif
#define PDIAGNOSTIC_IGNORE_UNUSED
#include "flatcc/portable/pdiagnostic_push.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct yella_boot_state_table *yella_boot_state_table_t;
typedef const flatbuffers_uoffset_t *yella_boot_state_vec_t;
typedef flatbuffers_uoffset_t *yella_boot_state_mutable_vec_t;



struct yella_boot_state_table { uint8_t unused__; };

#ifndef yella_boot_state_identifier
#define yella_boot_state_identifier flatbuffers_identifier
#endif
#define yella_boot_state_type_hash ((flatbuffers_thash_t)0xb26b0cee)
#define yella_boot_state_type_identifier "\xee\x0c\x6b\xb2"
static inline size_t yella_boot_state_vec_len(yella_boot_state_vec_t vec)
__flatbuffers_vec_len(vec)
static inline yella_boot_state_table_t yella_boot_state_vec_at(yella_boot_state_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(yella_boot_state_table_t, vec, i, 0)
__flatbuffers_table_as_root(yella_boot_state)

static inline uint32_t yella_boot_state_boot_count(yella_boot_state_table_t t)
__flatbuffers_scalar_field(flatbuffers_uint32, 0, 0, t)
static inline int yella_boot_state_boot_count_is_present(yella_boot_state_table_t t)
__flatbuffers_field_present(0, t)

static inline flatbuffers_uint8_vec_t yella_boot_state_uuid(yella_boot_state_table_t t)
__flatbuffers_vector_field(flatbuffers_uint8_vec_t, 1, t, 0)
static inline int yella_boot_state_uuid_is_present(yella_boot_state_table_t t)
__flatbuffers_field_present(1, t)


#include "flatcc/portable/pdiagnostic_pop.h"
#endif /* BOOT_STATE_H */
